language: python
cache: pip
python:
  - "2.7"
  - "3.5"
# command to install dependencies
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install --upgrade pip"
  - "pip install --upgrade setuptools"
  - "pip install --upgrade IPython"
  - "pip install -r etc/requirements.txt"
# command to run tests
script:
  - nosetests --with-coverage --cover-package=powerline
  - flake8 tests powerline
after_success:
  - coveralls
